name: Android CI/CD

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - main

jobs:
  build:
    name: Clean build
    runs-on: ubuntu-latest

    steps:
      - name: check out
        uses: actions/checkout@v2

      - name: setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: clean build
        run: ./gradlew clean build
        env:
          USER: ${{ secrets.USER }}
          TOKEN: ${{ secrets.TOKEN }}

      - name: upload dev apk
        uses: actions/upload-artifact@v1
        with:
          name: yk_verifier_dev.apk
          path: app/build/outputs/apk/dev/debug/app-dev-debug.apk

      - name: upload prod apk
        uses: actions/upload-artifact@v1
        with:
          name: yk_verifier_prod.apk
          path: app/build/outputs/apk/prod/debug/app-prod-debug.apk



